# Generated by Django 5.1.3 on 2024-11-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kind_Schoolvakken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
                ('Rekenen', models.CharField(max_length=50)),
                ('Taal', models.CharField(max_length=50)),
                ('Spelling', models.CharField(max_length=50)),
                ('Technisch_lezen', models.CharField(max_length=50)),
                ('Overig', models.CharField(max_length=75)),
            ],
        ),
    ]
