# Generated by Django 5.1.3 on 2024-11-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kaartjes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kind_schoolvakken',
            options={'verbose_name_plural': 'Kinderen en vakken'},
        ),
    ]
