# Generated by Django 5.1.3 on 2024-11-15 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behaaldstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleepdoel', models.BooleanField(default=False)),
                ('automatiseringsdoelen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Lessen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('les', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MomentVanVereisteBeheersing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Opmerkingen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opmerking', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Voorkennis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voorkennis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doelen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leerdoel', models.CharField(max_length=50)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schrijfjewijzer_app.kind')),
            ],
        ),
        migrations.CreateModel(
            name='MyInteger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('my_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='schrijfjewijzer_app.lessen')),
            ],
        ),
        migrations.CreateModel(
            name='SignaleringGroep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signalering', models.CharField(max_length=50)),
                ('doel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schrijfjewijzer_app.doelen')),
            ],
        ),
    ]
