# Generated by Django 5.1.3 on 2024-11-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schrijfjewijzer_app', '0002_blok_week_behaaldstatus_status_doelen_doel_kind_kind_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='behaaldstatus',
            old_name='status',
            new_name='status_blok',
        ),
        migrations.RenameField(
            model_name='doelen',
            old_name='doel',
            new_name='doel_blok',
        ),
        migrations.RenameField(
            model_name='kind',
            old_name='kind',
            new_name='kind_blok',
        ),
        migrations.RenameField(
            model_name='lessen',
            old_name='lessen',
            new_name='les_blok',
        ),
        migrations.RenameField(
            model_name='momentvanvereistebeheersing',
            old_name='moment_beheersing',
            new_name='moment_blok',
        ),
        migrations.RenameField(
            model_name='opmerkingen',
            old_name='opmerkingen',
            new_name='opmerking_blok',
        ),
        migrations.RenameField(
            model_name='signaleringgroep',
            old_name='signaleringgroep',
            new_name='signalering_blok',
        ),
        migrations.RenameField(
            model_name='voorkennis',
            old_name='kennis',
            new_name='kennis_blok',
        ),
        migrations.CreateModel(
            name='GenericRelationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('blok_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_links', to='schrijfjewijzer_app.blok_week')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
