# Generated by Django 5.1.3 on 2024-11-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrijfjewijzer_app', '0003_rename_status_behaaldstatus_status_blok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaaldstatus',
            name='status_blok',
            field=models.ManyToManyField(related_name='behaaldstatussen', to='schrijfjewijzer_app.blok_week'),
        ),
        migrations.AlterField(
            model_name='doelen',
            name='doel_blok',
            field=models.ManyToManyField(related_name='doelen', to='schrijfjewijzer_app.blok_week'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='kind_blok',
            field=models.ManyToManyField(related_name='kinderen', to='schrijfjewijzer_app.blok_week'),
        ),
        migrations.AlterField(
            model_name='lessen',
            name='les_blok',
            field=models.ManyToManyField(related_name='lessen', to='schrijfjewijzer_app.blok_week'),
        ),
        migrations.AlterField(
            model_name='momentvanvereistebeheersing',
            name='moment_blok',
            field=models.ManyToManyField(related_name='momenten', to='schrijfjewijzer_app.blok_week'),
        ),
        migrations.AlterField(
            model_name='opmerkingen',
            name='opmerking_blok',
            field=models.ManyToManyField(related_name='opmerkingen', to='schrijfjewijzer_app.blok_week'),
        ),
        migrations.AlterField(
            model_name='signaleringgroep',
            name='signalering_blok',
            field=models.ManyToManyField(related_name='signaleringen', to='schrijfjewijzer_app.blok_week'),
        ),
        migrations.AlterField(
            model_name='voorkennis',
            name='kennis_blok',
            field=models.ManyToManyField(related_name='voorkennis', to='schrijfjewijzer_app.blok_week'),
        ),
        migrations.DeleteModel(
            name='GenericRelationModel',
        ),
    ]
