# Generated by Django 5.1.3 on 2024-11-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrijfjewijzer_app', '0005_alter_behaaldstatus_options_alter_blok_week_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('lessen', models.JSONField()),
                ('leerdoel', models.CharField(max_length=50)),
                ('voorkennis', models.CharField(max_length=50)),
                ('signalering_kinderen', models.JSONField()),
                ('signalering_groep', models.CharField(max_length=50)),
                ('opmerkingen', models.CharField(blank=True, max_length=150, null=True)),
                ('sleepdoel', models.BooleanField(default=False)),
                ('automatiseringsdoelen', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Blokken',
            },
        ),
        migrations.RemoveField(
            model_name='doelen',
            name='doel_blok',
        ),
        migrations.RemoveField(
            model_name='lessen',
            name='les_blok',
        ),
        migrations.RemoveField(
            model_name='voorkennis',
            name='kennis_blok',
        ),
        migrations.RemoveField(
            model_name='momentvanvereistebeheersing',
            name='moment_blok',
        ),
        migrations.RemoveField(
            model_name='kind',
            name='kind_blok',
        ),
        migrations.RemoveField(
            model_name='signaleringgroep',
            name='signalering_blok',
        ),
        migrations.RemoveField(
            model_name='opmerkingen',
            name='opmerking_blok',
        ),
        migrations.RemoveField(
            model_name='doelen',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='signaleringgroep',
            name='doel',
        ),
        migrations.RemoveField(
            model_name='myinteger',
            name='my_model',
        ),
        migrations.DeleteModel(
            name='Behaaldstatus',
        ),
        migrations.DeleteModel(
            name='Voorkennis',
        ),
        migrations.DeleteModel(
            name='MomentVanVereisteBeheersing',
        ),
        migrations.DeleteModel(
            name='Blok_week',
        ),
        migrations.DeleteModel(
            name='Opmerkingen',
        ),
        migrations.DeleteModel(
            name='Kind',
        ),
        migrations.DeleteModel(
            name='Doelen',
        ),
        migrations.DeleteModel(
            name='SignaleringGroep',
        ),
        migrations.DeleteModel(
            name='Lessen',
        ),
        migrations.DeleteModel(
            name='MyInteger',
        ),
    ]
