# Generated by Django 5.1.3 on 2024-11-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrijfjewijzer_app', '0006_blok_remove_doelen_doel_blok_remove_lessen_les_blok_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blok',
            name='signalering_kinderen',
        ),
        migrations.AddField(
            model_name='blok',
            name='kind_1',
            field=models.CharField(blank=True, choices=[('Harry', 'Harry'), ('Barry', 'Barry'), ('Darry', 'Darry')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='blok',
            name='kind_2',
            field=models.CharField(blank=True, choices=[('Harry', 'Harry'), ('Barry', 'Barry'), ('Darry', 'Darry')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='blok',
            name='kind_3',
            field=models.CharField(blank=True, choices=[('Harry', 'Harry'), ('Barry', 'Barry'), ('Darry', 'Darry')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='blok',
            name='kind_4',
            field=models.CharField(blank=True, choices=[('Harry', 'Harry'), ('Barry', 'Barry'), ('Darry', 'Darry')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='blok',
            name='kind_5',
            field=models.CharField(blank=True, choices=[('Harry', 'Harry'), ('Barry', 'Barry'), ('Darry', 'Darry')], max_length=15, null=True),
        ),
    ]
