# Generated by Django 5.1.3 on 2024-11-17 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrijfjewijzer_app', '0008_remove_blok_leerdoel_blok_leerdoel_1_blok_leerdoel_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='blok',
            name='kind_1',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='kind_2',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='kind_3',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='kind_4',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='kind_5',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='leerdoel_1',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='leerdoel_2',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='leerdoel_3',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='leerdoel_4',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='leerdoel_5',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='signalering_groep',
        ),
        migrations.CreateModel(
            name='Leerdoel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doel', models.CharField(max_length=50)),
                ('blok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leerdoelen', to='schrijfjewijzer_app.blok')),
                ('kinderen', models.ManyToManyField(related_name='leerdoelen', to='schrijfjewijzer_app.kind')),
            ],
        ),
    ]
