# Generated by Django 5.1.3 on 2024-11-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrijfjewijzer_app', '0010_alter_kind_options_alter_leerdoel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blok',
            name='automatiseringsdoelen',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='lessen',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='opmerkingen',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='sleepdoel',
        ),
        migrations.RemoveField(
            model_name='blok',
            name='voorkennis',
        ),
        migrations.AddField(
            model_name='leerdoel',
            name='automatiseringsdoelen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leerdoel',
            name='lessen',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leerdoel',
            name='opmerkingen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leerdoel',
            name='sleepdoel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leerdoel',
            name='voorkennis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blok',
            name='bloknummer',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='blok',
            name='week',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
