# Generated by Django 5.1.3 on 2024-11-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrijfjewijzer_app', '0011_remove_blok_automatiseringsdoelen_remove_blok_lessen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='keuze1',
            field=models.IntegerField(choices=[(2, 'x'), (1, '~'), (0, 'v')], default=0),
        ),
        migrations.AddField(
            model_name='kind',
            name='keuze2',
            field=models.IntegerField(choices=[(2, 'x'), (1, '~'), (0, 'v')], default=0),
        ),
        migrations.AddField(
            model_name='kind',
            name='keuze3',
            field=models.IntegerField(choices=[(2, 'x'), (1, '~'), (0, 'v')], default=0),
        ),
    ]
