# Generated by Django 5.1.3 on 2024-11-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrijfjewijzer_app', '0013_remove_kind_keuze1_remove_kind_keuze2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leerdoel',
            name='automatiseringsdoelen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leerdoel',
            name='kinderen',
            field=models.ManyToManyField(related_name='leerdoelen', to='schrijfjewijzer_app.kind'),
        ),
        migrations.AddField(
            model_name='leerdoel',
            name='lessen',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leerdoel',
            name='opmerkingen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='leerdoel',
            name='sleepdoel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leerdoel',
            name='voorkennis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
