# Generated by Django 5.1.3 on 2024-11-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schrijfjewijzer_app', '0014_leerdoel_automatiseringsdoelen_leerdoel_kinderen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leerdoel',
            name='signalering_groep',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
